remote_theme: cotes2020/jekyll-theme-chirpy
title: Eco Inovação Brasil
description: Portal independente de notícias sobre sustentabilidade e economia circular
url: "https://ambisocial.github.io"
baseurl: "/eco-inovacao-brasil"
author: Redação Eco Inovação Brasil
email: contato@eco-inovacao-brasil.com
lang: pt-BR
timezone: America/Sao_Paulo
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives
markdown: kramdown
highlighter: rouge
paginate: 10
paginate_path: "/page:num/"
